# render.yaml
services:
  - type: web
    name: terabot
    env: docker
    repo: https://github.com/nvab-media/terabot
    branch: main
    envVars:
      - key: API_ID
        value: api_id
      - key: API_HASH
        value: api_hash
      - key: BOT_TOKEN
        value: bot_token
      - key: IMG_LINK
        value: image_link
      - key: PORT
        value: "8000"
    buildCommand: ""
    startCommand: ""
    plan: free
